# Archivo: eventos-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: eventos-config # <-- ¡ASEGÚRATE DE QUE ESTÉ ASÍ!
data:
  # ... el resto de tu configuración
  MONGO_URI: "mongodb://mongo:27017/"
  MONGO_DB_NAME: "eventosdb"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_TOPIC: "pacientes-topic"
  KAFKA_GROUP_ID: "eventos-consumer-group"