kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80  # El Ingress Controller dentro de Kind sigue escuchando en el puerto 80
    hostPort: 8080 # Pero en tu m치quina host (localhost) lo acceder치s por el puerto 8080
    protocol: TCP
  - containerPort: 443 # El Ingress Controller dentro de Kind sigue escuchando en el puerto 443
    hostPort: 8443 # Y en tu m치quina host (localhost) lo acceder치s por el puerto 8443
    protocol: TCP