version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:15-alpine
    container_name: postgres
    networks: # <-- AÑADIDO
      - sga-network # <-- AÑADIDO
    environment:
      POSTGRES_DB: farmacia
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: docker.io/library/mongo:6
    container_name: mongo
    networks: # <-- AÑADIDO
      - sga-network # <-- AÑADIDO
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    container_name: zookeeper
    networks: # <-- AÑADIDO
      - sga-network # <-- AÑADIDO
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: docker.io/bitnami/kafka:2.8.1
    container_name: kafka
    networks: # <-- AÑADIDO
      - sga-network # <-- AÑADIDO
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.25:9092 # <<< Asegúrate que esta sea la IP correcta de tu servidor
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xms512m -Xmx512m
    depends_on:
      - zookeeper

  pacientes:
    build:
      context: ./pacientes
    container_name: pacientes
    networks: # <-- AÑADIDO
      - sga-network # <-- AÑADIDO
    depends_on:
      - postgres
      - kafka
    env_file:
      - ./pacientes/.env
    ports:
      - "8000:8000"

  eventos:
    build:
      context: ./eventos
    container_name: eventos
    networks: # <-- AÑADIDO
      - sga-network # <-- AÑADIDO
    depends_on:
      - kafka
      - mongo
    env_file:
      - ./eventos/.env
    ports:
      - "8001:8001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks: # <-- AÑADIDO
      - sga-network # <-- AÑADIDO
    ports:
      - "3000:80"
    depends_on:
      - pacientes

volumes:
  pgdata:
  mongodata:

networks: # <-- AÑADIDO
  sga-network: # <-- AÑADIDO
    driver: bridge # <-- AÑADIDO
